"use client";

import { useState } from "react";
import { ArrowRight, Check, ChevronDown, Clock3, Heart, LockKeyhole, MapPin, MessageCircle, ShieldCheck, Sparkles, Stethoscope } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const whatsapp = "https://wa.me/6589968808";
const services = [["Individual counselling","Anxiety, stress, grief, burnout and life transitions."],["Couples counselling","Communicate with care, rebuild trust and move forward together."],["Family support","A calmer space for conflict, change and parenting pressures."],["For medical professionals","Support from someone who understands clinical work."]];

function Mark({light=false}:{light?:boolean}){return <a href="#top" className={`mark ${light?"mark-light":""}`}><span>THE</span><strong>EMBER</strong><span>PRACTICE</span></a>}
function CTA({children,pale=false}:{children:React.ReactNode,pale?:boolean}){return <a href={whatsapp} className={`cta ${pale?"pale":""}`} target="_blank" rel="noreferrer">{children}<ArrowRight size={17}/></a>}
function Trust({dark=false}:{dark?:boolean}){return <div className={`trust ${dark?"dark":""}`}><span><ShieldCheck/>Private & confidential</span><span><Stethoscope/>Former paediatric doctor</span><span><MapPin/>2 central locations</span><span><Clock3/>Online & in-person</span></div>}
function Enquiry({dark=false}:{dark?:boolean}){return <form className={`enquiry ${dark?"enquiry-dark":""}`} onSubmit={e=>{e.preventDefault();window.open(whatsapp,"_blank")}}><div className="form-top"><span>PRIVATE ENQUIRY</span><LockKeyhole/></div><h3>You don’t need the right words.</h3><p>Share only what feels comfortable. Sheetal will reply personally.</p><label>Your name<input required placeholder="How should we address you?"/></label><label>What would feel most helpful?<select defaultValue=""><option value="" disabled>Choose one</option><option>Individual support</option><option>Couples counselling</option><option>Family support</option><option>I’m not sure yet</option></select></label><button>Start a private conversation <ArrowRight/></button><small>No commitment. No clinical details required.</small></form>}
function Footer({dark=false}:{dark?:boolean}){return <footer className={dark?"footer-dark":""}><Mark light={dark}/><p>Therapy & counselling in Singapore</p><div><a href="mailto:hello@theemberpractice.com.sg">hello@theemberpractice.com.sg</a><a href="tel:+6568714390">+65 6871 4390</a></div><small>© 2026 The Ember Practice Pte Ltd · Not a crisis service</small></footer>}

function Editorial(){const offers=[
  ["01","Individual counselling","A private space to understand what you are carrying.","Stress, anxiety, burnout, self-worth, grief and life transitions."],
  ["02","Couples counselling","Communication, repair and understanding.","Slow difficult conversations, recognise patterns and reconnect without blame."],
  ["03","Family support","Navigate change, conflict and connection.","Help each person feel heard while building clearer, healthier communication."],
  ["04","Stress & burnout","When pressure has become too heavy.","Restore boundaries, emotional balance and a more sustainable way of living."],
  ["05","Online sessions","The same care, from your own space.","Secure, flexible support for privacy, travel and demanding schedules."],
  ["06","Corporate wellness","Healthier teams. Sustainable performance.","Counselling pathways, workshops, wellbeing talks and manager support."]
];return <main className="concept editorial editorial-v2" id="top"><nav><Mark/><div className="navlinks"><a href="#support">How we can help</a><a href="#approach">Your counsellor</a><a href="#visit">Locations</a><a href="#questions">FAQs</a></div><CTA>Book a session</CTA></nav>
<section className="v2-hero"><div className="v2-hero-copy"><p className="eyebrow">THERAPY & COUNSELLING · SINGAPORE</p><h1>Support for<br/><em>what life is</em><br/>asking of you.</h1><p>For individuals, couples and families who need a calm, confidential place to pause, understand and move forward.</p><div className="hero-actions"><CTA>Begin with a private enquiry</CTA><a href="#support">Explore support <ArrowRight/></a></div><small><LockKeyhole/>Online and in-person · Two central locations</small></div><div className="v2-hero-visual"><img src="/clarity-room.png" alt="A quiet counselling space overlooking Singapore"/><div className="floating-word">A space to<br/><i>feel heard.</i></div><div className="v2-badge"><span>500+</span><small>Counselling sessions</small></div></div></section>
<section className="opening-line"><p>If life has been feeling <em>overwhelming, heavy or uncertain,</em> you are not alone.</p><span>Therapy offers the space to pause, reflect and begin making meaningful change.</span></section><Trust/>
<section className="v2-services" id="support"><div className="v2-services-head"><p className="eyebrow">WAYS WE CAN WORK TOGETHER</p><h2>Start with what<br/>feels closest.</h2><p>You do not need to know the clinical name for what you are experiencing.</p></div><div className="offer-list">{offers.map((x,i)=><a href={whatsapp} key={x[0]} className={i===0?"featured":""}><span>{x[0]}</span><div><h3>{x[1]}</h3><b>{x[2]}</b><p>{x[3]}</p></div><ArrowRight/></a>)}</div></section>
<section className="healers"><div className="healers-image"><img src="/therapy-conversation.png" alt="A private and supportive counselling conversation"/><span>Private · Respectful · At your pace</span></div><div><p className="eyebrow">SUPPORT FOR THOSE WHO HEAL</p><h2>You matter,<br/><em>too.</em></h2><p>Medical practitioners carry the emotional weight of high-stakes decisions, demanding hours and caring for others. Sheetal’s own medical background creates a place where that reality does not need to be explained from the beginning.</p><CTA>Enquire confidentially</CTA></div></section>
<section className="v2-profile" id="approach"><div className="profile-intro"><p className="eyebrow">YOUR COUNSELLOR</p><h2>Medical understanding.<br/><em>Grounded human care.</em></h2></div><div className="profile-body"><p className="dropcap">I am Sheetal Singhania, a counsellor and former paediatric doctor with a Master’s in Counselling.</p><p>My work has always centred around understanding people—not just their symptoms, but their experiences, emotions and the context of their lives.</p><p>My style is warm, collaborative and non-judgemental. Sessions integrate CBT, ACT, mindfulness-based techniques and relationship-focused approaches around your individual needs.</p><a href={whatsapp}>See if this feels like the right space <ArrowRight/></a></div><aside><p>Training & experience</p><ul><li>Master’s in Counselling, Monash University</li><li>Graduate Certificate in Counselling, Monash University</li><li>MRCPCH (UK) · FCPS Paediatrics</li><li>MBBS, University of Mumbai</li><li>SAC Code of Ethics</li></ul></aside></section>
<section className="reflections"><p className="eyebrow">EXPERIENCES OF SUPPORT</p><div className="quote-stage"><span>“</span><blockquote>I felt heard and understood from the very first session. The space felt calm, safe and genuinely supportive.</blockquote><small>ANONYMOUS CLIENT FEEDBACK · SHARED WITH PERMISSION</small></div><div className="quote-peeks"><p>“The sessions helped me make sense of things I had been struggling with for a long time.”</p><p>“A thoughtful and grounded approach that helped me move forward with more clarity.”</p></div></section>
<section className="v2-process"><div><p className="eyebrow">A SIMPLE, COMFORTABLE PROCESS</p><h2>No pressure to<br/>have it all figured out.</h2></div><ol><li><span>01</span><div><h3>Initial contact</h3><p>Send a short enquiry through the website or WhatsApp.</p></div></li><li><span>02</span><div><h3>First conversation</h3><p>Understand your needs, goals and preferred session format.</p></div></li><li><span>03</span><div><h3>Counselling plan</h3><p>Agree on an approach that fits your situation.</p></div></li><li><span>04</span><div><h3>Ongoing support</h3><p>Work together at a safe, manageable pace.</p></div></li></ol></section>
<section className="v2-locations" id="visit"><header><p className="eyebrow">CHOOSE A CALM SPACE</p><h2>Central, discreet<br/>and easy to reach.</h2></header><div className="location-card"><span>01 · CBD / TANJONG PAGAR</span><h3>International Plaza</h3><p>10 Anson Road, #28-14<br/>Singapore 079903</p><b>EW15 Tanjong Pagar · Exit C</b></div><div className="location-card rust"><span>02 · CITY HALL / CIVIC DISTRICT</span><h3>High Street Centre</h3><p>1 North Bridge Road, #01-48<br/>Singapore 179094</p><b>NE5 Clarke Quay · EW13 City Hall</b></div><div className="online-note"><Clock3/><p><b>Prefer to stay at home?</b><br/>Secure online sessions offer the same care, structure and confidentiality.</p></div></section>
<section className="faq v2-faq" id="questions"><div><p className="eyebrow">BEFORE YOU REACH OUT</p><h2>A little clarity can make the first step easier.</h2><p>You are welcome to ask questions before deciding whether counselling feels right.</p></div><div>{[["Is counselling confidential?","Yes. Counselling is a private and respectful space, with limited safety or legal exceptions discussed clearly."],["How do I know if counselling is right for me?","A first session can help you explore that. You do not need to arrive with everything figured out."],["What happens in the first session?","We begin gently with what brings you here, what support you are looking for and what pace feels comfortable."],["Can sessions be online?","Yes. Sessions can be arranged in person or securely online, depending on preference and suitability."]].map((x,i)=><details key={x[0]} open={i===0}><summary>{x[0]}<ChevronDown/></summary><p>{x[1]}</p></details>)}</div></section><section className="v2-close"><div><p className="eyebrow">A GENTLE FIRST STEP</p><h2>You can begin with<br/>one short message.</h2><p>You deserve support and a space that feels safe.</p></div><Enquiry/></section><Footer/></main>}

function Guided(){const [choice,setChoice]=useState("myself");return <main className="concept guided" id="top"><nav><Mark/><div className="status"><span/>Accepting new enquiries</div><a className="message" href={whatsapp}>Speak privately <MessageCircle/></a></nav><section className="guided-hero"><div><p className="eyebrow">LET’S MAKE THIS SIMPLE</p><h1>What would you like<br/>support with today?</h1><p>You don’t need a diagnosis or a perfect explanation. Pick the closest starting point.</p><div className="choices">{[["myself","For myself","Stress, anxiety or feeling stuck"],["relationship","For my relationship","Communication, conflict or trust"],["family","For my family","Parenting, change or connection"],["unsure","I’m not sure","Help me understand my options"]].map(x=><button key={x[0]} onClick={()=>setChoice(x[0])} className={choice===x[0]?"active":""}><span>{x[1]}</span><small>{x[2]}</small><ArrowRight/></button>)}</div><a className="continue" href={whatsapp}>Continue with a private enquiry <ArrowRight/></a><small className="privacy"><LockKeyhole/>Takes less than a minute. Share only what feels comfortable.</small></div><aside><div className="monogram">S</div><p>YOUR COUNSELLOR</p><h2>Sheetal Singhania</h2><p>Counsellor & former paediatric doctor</p><hr/><blockquote>“A warm, collaborative space to feel heard without judgement.”</blockquote><ul><li><Check/>Evidence-based approach</li><li><Check/>Online or central Singapore</li><li><Check/>Adults, couples & families</li></ul></aside></section><Trust/>
<section className="relief"><div><p className="eyebrow">YOU MAY BE HERE BECAUSE…</p><h2>Something that used to feel manageable doesn’t anymore.</h2></div><div>{["Your mind rarely switches off","You and your partner keep reaching the same impasse","Work is taking more than you can give","A transition has left you feeling unsteady","You want change, but don’t know where to begin"].map((x,i)=><article key={x}><span>0{i+1}</span><p>{x}</p></article>)}</div></section>
<section className="reassure"><div className="room"><img src="/therapy-room.png" alt="Private counselling room"/></div><div><p className="eyebrow">WHAT TO EXPECT</p><h2>No pressure to perform.<br/>No judgement. No rush.</h2><p>The first session is a conversation. Together, you’ll understand what has brought you here and what support may be useful.</p><div className="checks"><span><Check/>You set the pace</span><span><Check/>Your goals shape the work</span><span><Check/>Questions are always welcome</span></div><CTA>Ask Sheetal a question</CTA></div></section>
<section className="locations"><p className="eyebrow">MEET YOUR WAY</p><h2>Close by, or from home.</h2><div>{[["01","International Plaza","10 Anson Road · Tanjong Pagar MRT, Exit C"],["02","High Street Centre","1 North Bridge Road · Near City Hall & Clarke Quay"],["03","Online","Private video sessions, wherever you feel comfortable."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="guided-close"><Heart/><h2>Start with one short message.</h2><p>You can simply say, “I’m looking for support.” That is enough.</p><CTA>Message Sheetal privately</CTA></section><Footer/></main>}

function Clinical(){return <main className="concept clinical" id="top"><nav><Mark light/><div className="navlinks"><a href="#care">Areas of care</a><a href="#sheetal">Your counsellor</a><a href="#visit">Visit</a></div><CTA pale>Confidential enquiry</CTA></nav><section className="hero clinical-hero"><div><p className="eyebrow">THE EMBER PRACTICE · SINGAPORE</p><h1>Care for the life<br/>behind the symptoms.</h1><p className="lede">Private, evidence-based counselling for individuals, couples and families—grounded in clinical understanding and human connection.</p><div className="hero-actions"><CTA pale>Arrange a first conversation</CTA><a href="tel:+6568714390">or call +65 6871 4390</a></div></div><div className="photo"><img src="/therapy-room.png" alt="A discreet modern therapy room"/><div className="availability"><span/>Appointments available<br/><b>Online & in person</b></div></div></section><Trust dark/>
<section className="care" id="care"><div><p className="eyebrow">AREAS OF CARE</p><h2>Space for what matters now.</h2><p>Support is tailored—not templated—to your circumstances, needs and pace.</p></div><div>{services.map((x,i)=><article key={x[0]}><span>0{i+1}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div><a href={whatsapp}><ArrowRight/></a></article>)}</div></section>
<section className="doctor" id="sheetal"><div><span>MBBS · MRCPCH (UK) · MASTER’S IN COUNSELLING</span><h2>A rare perspective on care.</h2><p>Before becoming a counsellor, Sheetal Singhania worked as a paediatric doctor in the United Kingdom. Today, she integrates that clinical foundation with CBT, ACT, mindfulness and relationship-focused therapy.</p><CTA pale>Read Sheetal’s approach</CTA></div><blockquote>“Understanding people—not just their symptoms, but their experiences and the context of their lives.”</blockquote></section>
<section className="proof"><div><strong>500+</strong><span>Counselling sessions</span></div><div><strong>2</strong><span>Central locations</span></div><div><strong>1:1</strong><span>Continuity of care</span></div><div><strong>SAC</strong><span>Ethical standards</span></div></section><section className="visit" id="visit"><div><p className="eyebrow">YOUR FIRST SESSION</p><h2>Clear, discreet,<br/>at your pace.</h2><p>Begin with a short enquiry. You’ll hear directly from Sheetal about availability, format and whether the practice feels like the right fit.</p></div><Enquiry dark/></section><Footer dark/></main>}

export default function Home(){return <Tabs defaultValue="editorial" className="shell"><div className="switcher"><span>THREE DESIGN DIRECTIONS</span><TabsList><TabsTrigger value="editorial">01 Editorial Calm</TabsTrigger><TabsTrigger value="guided">02 Guided Start</TabsTrigger><TabsTrigger value="clinical">03 Clinical Atelier</TabsTrigger></TabsList></div><TabsContent value="editorial"><Editorial/></TabsContent><TabsContent value="guided"><Guided/></TabsContent><TabsContent value="clinical"><Clinical/></TabsContent></Tabs>}
